name: build

on:
  push:

jobs:
  macos:
    strategy:
      matrix:
        macos:
          - 13
        xcode:
          - 14.3
    runs-on: macos-${{ matrix.macos }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Build
        run:
          swift build -c debug
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
