name: build
        
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

on:
  push:

jobs:
  macos:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Bootstrap
        run: 
          make bootstrap
      - name: Build
        run:
          make build
