name: release
        
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

on:
  workflow_dispatch:

jobs:
  macos:
    permissions:
      contents: write
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Bootstrap
        run: |
          make bootstrap
      - name: Archive
        run: |
          make archive
      - name: Setup version
        id: version
        run: |
          echo "::set-output name=version::$(cat version.txt)"
      - name: Create Git Tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
      - name: Create Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${{ steps.version.outputs.version }}\", \"name\": \"${{ steps.version.outputs.version }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/releases
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # - name: Upload Release Asset
      #   run: |
      #     VERSION=${{ steps.version.outputs.version }}
      #     RELEASE_ID=$(curl --request GET \
      #       --url https://api.github.com/repos/yuta24/swift-analyzer/releases/tags/$VERSION \
      #       --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
      #       | jq -r '.id')
      #     curl --http1.1 --request POST \
      #       --url https://uploads.github.com/repos/yuta24/swift-analyzer/releases/$RELEASE_ID/assets?name=swift-analyzer.zip \
      #       --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
      #       --header 'content-type: application/zip' \
      #       --data-binary '@swift-analyzer.zip'
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
